name: 'Configure Docker'
description: 'Set up Docker Buildx and configure build args'
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          network=host

    # This is required to allow buildkit to access the actions cache
    - name: Expose actions cache variables
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])

    - name: Set docker build args
      shell: bash
      run: |
        # Only set to gha style cache to use cirrus's cache if running on the testing-cirrus-runners/bitcoin2 repo
        # On forks the gha cache will work but will use Github's cache backend
        if [[ "${{ github.repository }}" == "testing-cirrus-runners/bitcoin2" ]]; then
          URL_ARGS="url=${{ env.CIRRUS_CACHE_HOST }},url_v2=${{ env.CIRRUS_CACHE_HOST }}"
        else
          # Docker will check for actions variables $ACTIONS_CACHE_URL, $ACTIONS_RESULTS_URL and $ACTIONS_RUNTIME_TOKEN if not otherwise set.
          # These are set automatically when running on GitHub infra: https://docs.docker.com/build/cache/backends/gha/#synopsis
          URL_ARGS=""
        fi

        if [[ "${{ (github.event_name == 'push') && (github.ref_name == github.event.repository.default_branch) }}" == "true" ]]; then
          echo "DOCKER_BUILD_CACHE_ARG=--cache-from type=gha,$URL_ARGS,scope=${{ env.CONTAINER_NAME }} --cache-to type=gha,$URL_ARGS,mode=max,scope=${{ env.CONTAINER_NAME }} --load" >> $GITHUB_ENV
        else
          echo "DOCKER_BUILD_CACHE_ARG=--cache-from type=gha,$URL_ARGS,scope=${{ env.CONTAINER_NAME }} --load" >> $GITHUB_ENV
        fi
